# Generated by Django 5.1.7 on 2025-04-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_average_activity_report_average_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='average_activity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='average_temperature',
        ),
    ]
