# Generated by Django 5.1.7 on 2025-04-23 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_report_average_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.AddField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
