# Generated by Django 5.1.7 on 2025-04-26 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_temperaturereading_report_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('activity_level', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.pig')),
            ],
        ),
        migrations.DeleteModel(
            name='TemperatureReading',
        ),
        migrations.RemoveField(
            model_name='report',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='report',
            name='treatment',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
