# Generated by Django 5.1.7 on 2025-04-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_type',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dosage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
