# Generated by Django 5.1.7 on 2025-04-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_remove_treatment_treatment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='dosage',
            new_name='treatment_type',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='medication',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='notes',
            field=models.TextField(default='No notes'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='pig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatment.pig'),
        ),
    ]
