# Generated by Django 5.1.7 on 2025-04-10 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='activity_level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
