# Generated by Django 5.1.7 on 2025-04-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='weight',
        ),
    ]
