# Generated by Django 5.1.7 on 2025-04-26 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='feeding_reminder',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='temperature_alert',
        ),
        migrations.AddField(
            model_name='alert',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.TextField(default='No message provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='pig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.pig'),
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
