# Generated by Django 5.1.7 on 2025-04-10 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperature', models.CharField(default='N/A', max_length=20)),
                ('activity', models.CharField(default='N/A', max_length=20)),
                ('weight', models.CharField(default='N/A', max_length=20)),
                ('health_status', models.CharField(default='Unknown', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
